server:
  port: 8080

spring:
  application:
    name: STORE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/store_db
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true



